[package]
name = "starcoin-move-prover"
version = "1.11.10"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
## move dependencies
move-prover = { git = "https://github.com/starcoinorg/move", rev = "4b14536a31a0c37db77e631988831bb54953d13c"  }

# external dependencies
tempfile = "3.2.0"
codespan-reporting = "0.11"
atty = "0.2.14"
anyhow = "1.0.41"

[dev-dependencies]
datatest-stable = "0.1.1"
move-prover-test-utils = {git = "https://github.com/starcoinorg/move", rev = "4b14536a31a0c37db77e631988831bb54953d13c"  }
move-command-line-common= {git = "https://github.com/starcoinorg/move", rev = "4b14536a31a0c37db77e631988831bb54953d13c" }
shell-words = "1.0.0"
walkdir = "2.3"
once_cell = "1.12.0"
tempfile = "3.2"

itertools = "0.10.3"
hex = "0.4.3"
clap = { version = "3", features = ["derive"] }
log = "0.4.16"
num = "0.4.0"
pretty = "0.10.0"
rand = "0.8.5"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.61"
simplelog = "0.9.0"
toml = "0.5.9"

[[test]]
name = "testsuite"
harness = false

