[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-resource-viewer"
publish = false
version = "1.11.11"

[dependencies]
anyhow = "1.0.41"
hex = "0.4.3"
move-binary-format = { git = "https://github.com/JerryKwan/move-starcoin", rev = "f4086a5517de269d320865d86081eb7aedfa7037" }
move-core-types = { git = "https://github.com/JerryKwan/move-starcoin", rev = "f4086a5517de269d320865d86081eb7aedfa7037" }
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_json = "1.0"
starcoin-vm-types = { path = "../types" }
