[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-proptest-helpers"
publish = false
version = "1.11.11"

[dependencies]
crossbeam = "0.7.3"
diem-proptest-helpers = { package = "diem-proptest-helpers", git = "https://github.com/JerryKwan/move-starcoin", rev = "f4086a5517de269d320865d86081eb7aedfa7037" }

proptest = "1.0.0"
proptest-derive = "0.3.0"
